### ISSUE TITLE
[BUG] 클러스터 생성 시 의도치 않은 생성

### ISSUE THREAD

**Issue by qhrms97** [kakao-cloud-k8s-project-kukudas/aws_final_project_web#24]
관련 이슈: 클러스터 생성 버튼 클릭 후 배포이후, 원치 않게 또 생성이 되는 문제가 있음
- 생성이 다 된 것도 아님

**Comment by qhrms97** [comment]
[버그 추적 계획]

> Django 에서 해당 버튼 클릭 로그 확인 예정
> 서버 쉘 파일 동작 확인

**Comment by white-onne** [comment]
생성 시 return값이 render라서 문제 인 듯! 화면 새로고침 시, /home/create url가 유지된다. 
redirect('/home')으로 변경하면 될 듯

**Comment by qhrms97** [comment]
22일 오전 클러스터 생성 확인 필요

> 클러스터 중복 생성 안되는지 확인 완료
